### ISSUE TITLE
Prompting to save document before export/run

### ISSUE THREAD

**Issue by githubchan0** [SetTrend/Raw-Image-Converter#1]
How to remove this? I don't need to save the document, I need to run the script right on way

![2023-07-28 18_28_07-Script Alert](https://github.com/SetTrend/Raw-Image-Converter/assets/127070736/9eded75b-3f8b-40dc-b779-a9c87f37e61e)

**Comment by SetTrend** [comment]
Hi @githubchan0,

thanks for raising this issue!

The script is mainly based on using CameraRaw features. CameraRaw can only act on files saved to disk. That's why you need to save your images first before using the script.

You may want to create a PhotoShop Action that's matching your needs for unsaved files.
